services:
  # Сервис базы данных
  db:
    image: postgres:17-alpine
    container_name: taskflow_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskflow
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # Визуальный интерфейс для управления БД
  pgadmin:
    image: dpage/pgadmin4
    container_name: taskflow_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80" # Будет доступен по адресу http://localhost:8081
    depends_on:
      - db
