spring:
  application:
    name: TaskFlow - Backend
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5433/taskflow
    username: user
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: user
    password: password
    url: jdbc:postgresql://localhost:5433/taskflow

logging:
  level:
    org.flywaydb: DEBUG          # ← увидишь, запускается ли Flyway и что он делает
    org.springframework.jdbc: DEBUG


