services:

  backend:
    ports:
      - "8080:8080"

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  # Redis GUI — открывается на http://localhost:5540
  redis-insight:
    image: redis/redisinsight:latest
    container_name: taskflow_redis_insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
