ktor:
    application:
        modules:
            - vrsalex.app.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://taskflow.ru"
  audience: "taskflow-user"
  realm: "TaskFlow user realm"
  secret: "${JWT_SECRET}"
  expiration: 2592000000
  refreshExpiration: 2592000000

db:
  user: user
  password: password
  db_name: taskflow
  port: 5433
  host: localhost
  poolConnectionCount: 5
  poolConnectionMaxCount: 35
